### PR TITLE
New Menu UI | Added Options Menu

### PR DESCRIPTION
**Pull request by Fatiz**
MAIN MENU: http://puu.sh/jfi5Q/4aad4040a6.png
OPTIONS MENU: http://puu.sh/jfi81/0b0f807c9d.png
INSTRUCTIONS MENU http://puu.sh/jfi8Z/340f505c62.png
New menu UI flash back to realms UI.
Added options menu allow user to enable and disable music.

Misc: Changed the code for making buttons to allow for more
customization with Font size and Color etc.

Known bugs: Hitboxes on some of the buttons need to be fixed also some
aligning of some buttons to make symmetrical

### CODE REVIEW

**Comment by DanielDees** [comment]
I like the code, good ideas there!

**Comment by Fatiz** [comment]
So I should go about a different way of doing the enable/disable music?

**Comment by DanielDees** [comment]
The way I did it in the last one was basically have a button that when clicked if (music is muted) {unmute} else {mute}

**Comment by Fatiz** [comment]
Yeah I kinda brain farted that one and did quite a big work around

**Comment by DanielDees** [comment]
How do I put up a pull request like you did to show you my version?

**Comment by DanielDees** [comment]
I've been messing around with stuff but I think I might be messing up stuff instead of figuring it out.

**Comment by Fatiz** [comment]
What I use is the git hub windows desktop version so with that you can see here http://puu.sh/jfwWx/a42fc7bca9.png I add the repository that I have on my pc and when ever I make a change it shows up there with a summary and description for me to write then I can submit that change and click the sync button(top right) to sync. After its synced on the website you can publish a pull request but for you I don't think you need to(You can probably do it anyway) and that's how

**Comment by DanielDees** [comment]
Ok, check out my new commit. I reworked some of the stuff  you added.

**Pull request closed without merging**
