### PR TITLE
Update UI

### PR DESCRIPTION
**Pull request by DanielDees**
Please tell me I did this correctly

### CODE REVIEW

**Comment by Fatiz** [comment]
All looks good the only problems I see are on my end the buttons are fucked http://puu.sh/jfyBP/3a05eca856.png Notice start and instructions http://puu.sh/jfyCT/17f6e8a805.png

**Comment by DanielDees** [comment]
I know, thats how the buttons were before but I just made the hit boxes for them visible.
The problem lies in the ctx.measuretext thing I am using. I should be getting the right values for the witdth of the text, but the button isn't getting that wide. You can see how it is supposed to work here: http://www.w3schools.com/tags/canvas_measuretext.asp

**Comment by DanielDees** [comment]
Since the button width for the hit box is supposed to equal the ctx.measuretext, something is obviously not measuring correctly.

**Comment by Fatiz** [comment]
Ok I could be completely wrong here but what it looks to me is that the measure is not taking into account font size you can see by increasing font size does nothing to hitbox its almost as the font size for measuring is set at a certain value will look into more.

**Comment by DanielDees** [comment]
Ok, then maybe one idea will be to find out what the default font size that measure text uses is and then add a multiplier.

So if default is 20px, then 

var currentfontsize = whatever the passed font size is
 var buttonwidth = ctx.measuretext(text).width * (currentfontsize / 20);

**Comment by Fatiz** [comment]
Thats a great idea will try it out

**Comment by DanielDees** [comment]
Sweet thanks!

I gotta go to sleep soon/do a workout so I will check in tomorrow

Also, I will be able to do a lot of coding tomorrow since I am off work tomorrow.

**Comment by Fatiz** [comment]
Ok great im off to bed in like 2 hours so ill see what I can get done and will post results!

**Comment by DanielDees** [comment]
Hey, btw you seem like a decent coder, what is your coding experience/ what do you know?

**Comment by Fatiz** [comment]
Not anything worthy.. I used to do coding for Gmod dark rp servers for free in lua and learned JS and html on the side. Also coded some games in LUA also.

**Pull request merged**
